import { ErrorBoundary } from '@/components/error-boundary';
import { AppProviders } from '@/components/providers';
import { IntlProvider } from '@/components/providers/intl-provider';
import type { Metadata } from 'next';
import { getMessages } from 'next-intl/server';
import { Geist, Geist_Mono } from 'next/font/google';
import Script from 'next/script';
import NextTopLoader from 'nextjs-toploader';
import 'shared-ui/styles.css';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const messages = await getMessages();

  return (
    <html lang="vi" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Script
          id="locale-sync"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  // Check if user has a preferred locale in localStorage
                  var storedLocale = localStorage.getItem('locale');
                  var currentLocale = document.documentElement.lang || 'vi';

                  // Update HTML lang attribute immediately
                  if (storedLocale && ['en', 'vi'].includes(storedLocale)) {
                    document.documentElement.lang = storedLocale;

                    // If stored locale differs from server-rendered locale, reload once
                    if (storedLocale !== currentLocale) {
                      var reloadKey = 'locale_reload_' + storedLocale;
                      if (!sessionStorage.getItem(reloadKey)) {
                        sessionStorage.setItem(reloadKey, '1');
                        window.location.reload();
                      }
                    }
                  }
                } catch (e) {
                  // Ignore errors in SSR or if storage is not available
                }
              })();
            `,
          }}
        />
        <ErrorBoundary>
          <NextTopLoader showSpinner={false} height={3} color="#d92d20" easing="ease" speed={200} />
          <IntlProvider initialMessages={messages}>
            <AppProviders>{children}</AppProviders>
          </IntlProvider>
        </ErrorBoundary>
      </body>
    </html>
  );
}
